window.PLANNER_TASKS = [
  {
    "id": 1,
    "atividade": "Alinhamento inicial das ações",
    "descricao": "Definir entregáveis e responsáveis.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-06-23",
    "proximaAcao": "Realizar alinhamento inicial com os envolvidos.",
    "observacoes": "Definir entregáveis e responsáveis.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 2,
    "atividade": "Mapeamento de eventos e competições",
    "descricao": "Consolidar informações em uma única base.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-06-26",
    "proximaAcao": "Levantar eventos, competições e datas-chave.",
    "observacoes": "Consolidar informações em uma única base.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 3,
    "atividade": "Plano de comunicação",
    "descricao": "Incluir comunicação interna e externa, se aplicável.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-06-30",
    "proximaAcao": "Estruturar mensagens, canais e calendário de divulgação.",
    "observacoes": "Incluir comunicação interna e externa, se aplicável.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 4,
    "atividade": "Produção de peças visuais",
    "descricao": "Garantir aplicação correta da marca SESI.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-06",
    "proximaAcao": "Definir lista de peças e formatos necessários.",
    "observacoes": "Garantir aplicação correta da marca SESI.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 5,
    "atividade": "Captação de conteúdo",
    "descricao": "Prever autorizações de imagem quando necessário.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-08",
    "proximaAcao": "Planejar fotos, vídeos, entrevistas e registros de bastidores.",
    "observacoes": "Prever autorizações de imagem quando necessário.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 6,
    "atividade": "Ativação de marca em quadra",
    "descricao": "Validar layout antes da produção final.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-13",
    "proximaAcao": "Validar layout de aplicação de marca em quadra.",
    "observacoes": "Validar layout antes da produção final.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 7,
    "atividade": "Relacionamento com atletas e comissão",
    "descricao": "Registrar pontos de atenção por equipe/categoria.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-16",
    "proximaAcao": "Mapear contatos, demandas e pontos de atenção.",
    "observacoes": "Registrar pontos de atenção por equipe/categoria.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 8,
    "atividade": "Plano de mídia e divulgação",
    "descricao": "Priorizar datas estratégicas.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-20",
    "proximaAcao": "Organizar calendário editorial e prioridades de publicação.",
    "observacoes": "Priorizar datas estratégicas.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 9,
    "atividade": "Controle de materiais e uniformes",
    "descricao": "Incluir justificativas e aprovações quando aplicável.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-07-23",
    "proximaAcao": "Conferir materiais, uniformes, aprovações e pendências.",
    "observacoes": "Incluir justificativas e aprovações quando aplicável.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 10,
    "atividade": "Execução das ações",
    "descricao": "Criar checklist de operação para cada ação.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-08-02",
    "proximaAcao": "Criar checklist operacional por ação.",
    "observacoes": "Criar checklist de operação para cada ação.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 11,
    "atividade": "Monitoramento de resultados",
    "descricao": "Utilizar indicadores simples e comparáveis.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-08-07",
    "proximaAcao": "Definir indicadores de acompanhamento e rotina de análise.",
    "observacoes": "Utilizar indicadores simples e comparáveis.",
    "ultimaAtualizacao": ""
  },
  {
    "id": 12,
    "atividade": "Relatório final",
    "descricao": "Preparar versão executiva para apresentação.",
    "responsavel": "",
    "prioridade": "Média",
    "status": "Não iniciado",
    "andamento": 0,
    "inicioPlanejado": "",
    "prazo": "2026-08-17",
    "proximaAcao": "Organizar registros, indicadores e aprendizados finais.",
    "observacoes": "Preparar versão executiva para apresentação.",
    "ultimaAtualizacao": ""
  }
];
